//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Vtl.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VtlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IVtlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] VtlParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>temporaryAssignment</c>
	/// labeled alternative in <see cref="VtlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemporaryAssignment([NotNull] VtlParser.TemporaryAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>persistAssignment</c>
	/// labeled alternative in <see cref="VtlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPersistAssignment([NotNull] VtlParser.PersistAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defineExpression</c>
	/// labeled alternative in <see cref="VtlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefineExpression([NotNull] VtlParser.DefineExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varIdExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarIdExpr([NotNull] VtlParser.VarIdExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>membershipExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMembershipExpr([NotNull] VtlParser.MembershipExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inNotInExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInNotInExpr([NotNull] VtlParser.InNotInExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>booleanExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExpr([NotNull] VtlParser.BooleanExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comparisonExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpr([NotNull] VtlParser.ComparisonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] VtlParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionsExpression</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionsExpression([NotNull] VtlParser.FunctionsExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfExpr([NotNull] VtlParser.IfExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>clauseExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClauseExpr([NotNull] VtlParser.ClauseExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arithmeticExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpr([NotNull] VtlParser.ArithmeticExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpr([NotNull] VtlParser.ParenthesisExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constantExpr</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpr([NotNull] VtlParser.ConstantExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arithmeticExprOrConcat</c>
	/// labeled alternative in <see cref="VtlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExprOrConcat([NotNull] VtlParser.ArithmeticExprOrConcatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arithmeticExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExprComp([NotNull] VtlParser.ArithmeticExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfExprComp([NotNull] VtlParser.IfExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comparisonExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExprComp([NotNull] VtlParser.ComparisonExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionsExpressionComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionsExpressionComp([NotNull] VtlParser.FunctionsExpressionCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compId</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompId([NotNull] VtlParser.CompIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constantExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExprComp([NotNull] VtlParser.ConstantExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arithmeticExprOrConcatComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExprOrConcatComp([NotNull] VtlParser.ArithmeticExprOrConcatCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExprComp([NotNull] VtlParser.ParenthesisExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inNotInExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInNotInExprComp([NotNull] VtlParser.InNotInExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExprComp([NotNull] VtlParser.UnaryExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>booleanExprComp</c>
	/// labeled alternative in <see cref="VtlParser.exprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExprComp([NotNull] VtlParser.BooleanExprCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>genericFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericFunctionsComponents([NotNull] VtlParser.GenericFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringFunctionsComponents([NotNull] VtlParser.StringFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numericFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericFunctionsComponents([NotNull] VtlParser.NumericFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comparisonFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonFunctionsComponents([NotNull] VtlParser.ComparisonFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeFunctionsComponents([NotNull] VtlParser.TimeFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>conditionalFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalFunctionsComponents([NotNull] VtlParser.ConditionalFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggregateFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFunctionsComponents([NotNull] VtlParser.AggregateFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>analyticFunctionsComponents</c>
	/// labeled alternative in <see cref="VtlParser.functionsComponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnalyticFunctionsComponents([NotNull] VtlParser.AnalyticFunctionsComponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>joinFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinFunctions([NotNull] VtlParser.JoinFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>genericFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericFunctions([NotNull] VtlParser.GenericFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringFunctions([NotNull] VtlParser.StringFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numericFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericFunctions([NotNull] VtlParser.NumericFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comparisonFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonFunctions([NotNull] VtlParser.ComparisonFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeFunctions([NotNull] VtlParser.TimeFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>setFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetFunctions([NotNull] VtlParser.SetFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>hierarchyFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchyFunctions([NotNull] VtlParser.HierarchyFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>validationFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidationFunctions([NotNull] VtlParser.ValidationFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>conditionalFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalFunctions([NotNull] VtlParser.ConditionalFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggregateFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFunctions([NotNull] VtlParser.AggregateFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>analyticFunctions</c>
	/// labeled alternative in <see cref="VtlParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnalyticFunctions([NotNull] VtlParser.AnalyticFunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasetClause([NotNull] VtlParser.DatasetClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRenameClause([NotNull] VtlParser.RenameClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.aggrClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrClause([NotNull] VtlParser.AggrClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilterClause([NotNull] VtlParser.FilterClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcClause([NotNull] VtlParser.CalcClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.keepOrDropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeepOrDropClause([NotNull] VtlParser.KeepOrDropClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.pivotOrUnpivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPivotOrUnpivotClause([NotNull] VtlParser.PivotOrUnpivotClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.customPivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomPivotClause([NotNull] VtlParser.CustomPivotClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.subspaceClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubspaceClause([NotNull] VtlParser.SubspaceClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>joinExpr</c>
	/// labeled alternative in <see cref="VtlParser.joinOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinExpr([NotNull] VtlParser.JoinExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defOperator</c>
	/// labeled alternative in <see cref="VtlParser.defOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefOperator([NotNull] VtlParser.DefOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defDatapointRuleset</c>
	/// labeled alternative in <see cref="VtlParser.defOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefDatapointRuleset([NotNull] VtlParser.DefDatapointRulesetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defHierarchical</c>
	/// labeled alternative in <see cref="VtlParser.defOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefHierarchical([NotNull] VtlParser.DefHierarchicalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>callDataset</c>
	/// labeled alternative in <see cref="VtlParser.genericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallDataset([NotNull] VtlParser.CallDatasetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>evalAtom</c>
	/// labeled alternative in <see cref="VtlParser.genericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalAtom([NotNull] VtlParser.EvalAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>castExprDataset</c>
	/// labeled alternative in <see cref="VtlParser.genericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExprDataset([NotNull] VtlParser.CastExprDatasetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>callComponent</c>
	/// labeled alternative in <see cref="VtlParser.genericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallComponent([NotNull] VtlParser.CallComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>castExprComponent</c>
	/// labeled alternative in <see cref="VtlParser.genericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExprComponent([NotNull] VtlParser.CastExprComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>evalAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.genericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalAtomComponent([NotNull] VtlParser.EvalAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.parameterComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterComponent([NotNull] VtlParser.ParameterComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] VtlParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryStringFunction</c>
	/// labeled alternative in <see cref="VtlParser.stringOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryStringFunction([NotNull] VtlParser.UnaryStringFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>substrAtom</c>
	/// labeled alternative in <see cref="VtlParser.stringOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubstrAtom([NotNull] VtlParser.SubstrAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>replaceAtom</c>
	/// labeled alternative in <see cref="VtlParser.stringOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplaceAtom([NotNull] VtlParser.ReplaceAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>instrAtom</c>
	/// labeled alternative in <see cref="VtlParser.stringOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrAtom([NotNull] VtlParser.InstrAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryStringFunctionComponent</c>
	/// labeled alternative in <see cref="VtlParser.stringOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryStringFunctionComponent([NotNull] VtlParser.UnaryStringFunctionComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>substrAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.stringOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubstrAtomComponent([NotNull] VtlParser.SubstrAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>replaceAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.stringOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplaceAtomComponent([NotNull] VtlParser.ReplaceAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>instrAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.stringOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrAtomComponent([NotNull] VtlParser.InstrAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryNumeric</c>
	/// labeled alternative in <see cref="VtlParser.numericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryNumeric([NotNull] VtlParser.UnaryNumericContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryWithOptionalNumeric</c>
	/// labeled alternative in <see cref="VtlParser.numericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryWithOptionalNumeric([NotNull] VtlParser.UnaryWithOptionalNumericContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryNumeric</c>
	/// labeled alternative in <see cref="VtlParser.numericOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryNumeric([NotNull] VtlParser.BinaryNumericContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryNumericComponent</c>
	/// labeled alternative in <see cref="VtlParser.numericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryNumericComponent([NotNull] VtlParser.UnaryNumericComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryWithOptionalNumericComponent</c>
	/// labeled alternative in <see cref="VtlParser.numericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryWithOptionalNumericComponent([NotNull] VtlParser.UnaryWithOptionalNumericComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryNumericComponent</c>
	/// labeled alternative in <see cref="VtlParser.numericOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryNumericComponent([NotNull] VtlParser.BinaryNumericComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>betweenAtom</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetweenAtom([NotNull] VtlParser.BetweenAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>charsetMatchAtom</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharsetMatchAtom([NotNull] VtlParser.CharsetMatchAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>isNullAtom</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsNullAtom([NotNull] VtlParser.IsNullAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>existInAtom</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExistInAtom([NotNull] VtlParser.ExistInAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>betweenAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetweenAtomComponent([NotNull] VtlParser.BetweenAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>charsetMatchAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharsetMatchAtomComponent([NotNull] VtlParser.CharsetMatchAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>isNullAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.comparisonOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsNullAtomComponent([NotNull] VtlParser.IsNullAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>periodAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPeriodAtom([NotNull] VtlParser.PeriodAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fillTimeAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFillTimeAtom([NotNull] VtlParser.FillTimeAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>flowAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlowAtom([NotNull] VtlParser.FlowAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeShiftAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeShiftAtom([NotNull] VtlParser.TimeShiftAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeAggAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeAggAtom([NotNull] VtlParser.TimeAggAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>currentDateAtom</c>
	/// labeled alternative in <see cref="VtlParser.timeOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCurrentDateAtom([NotNull] VtlParser.CurrentDateAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>periodAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPeriodAtomComponent([NotNull] VtlParser.PeriodAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fillTimeAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFillTimeAtomComponent([NotNull] VtlParser.FillTimeAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>flowAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlowAtomComponent([NotNull] VtlParser.FlowAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeShiftAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeShiftAtomComponent([NotNull] VtlParser.TimeShiftAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>timeAggAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeAggAtomComponent([NotNull] VtlParser.TimeAggAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>currentDateAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.timeOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCurrentDateAtomComponent([NotNull] VtlParser.CurrentDateAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unionAtom</c>
	/// labeled alternative in <see cref="VtlParser.setOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionAtom([NotNull] VtlParser.UnionAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intersectAtom</c>
	/// labeled alternative in <see cref="VtlParser.setOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntersectAtom([NotNull] VtlParser.IntersectAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>setOrSYmDiffAtom</c>
	/// labeled alternative in <see cref="VtlParser.setOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetOrSYmDiffAtom([NotNull] VtlParser.SetOrSYmDiffAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.hierarchyOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchyOperators([NotNull] VtlParser.HierarchyOperatorsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>validateDPruleset</c>
	/// labeled alternative in <see cref="VtlParser.validationOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidateDPruleset([NotNull] VtlParser.ValidateDPrulesetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>validateHRruleset</c>
	/// labeled alternative in <see cref="VtlParser.validationOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidateHRruleset([NotNull] VtlParser.ValidateHRrulesetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>validationSimple</c>
	/// labeled alternative in <see cref="VtlParser.validationOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidationSimple([NotNull] VtlParser.ValidationSimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nvlAtom</c>
	/// labeled alternative in <see cref="VtlParser.conditionalOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNvlAtom([NotNull] VtlParser.NvlAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nvlAtomComponent</c>
	/// labeled alternative in <see cref="VtlParser.conditionalOperatorsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNvlAtomComponent([NotNull] VtlParser.NvlAtomComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggrComp</c>
	/// labeled alternative in <see cref="VtlParser.aggrOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrComp([NotNull] VtlParser.AggrCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>countAggrComp</c>
	/// labeled alternative in <see cref="VtlParser.aggrOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCountAggrComp([NotNull] VtlParser.CountAggrCompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggrDataset</c>
	/// labeled alternative in <see cref="VtlParser.aggrOperatorsGrouping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrDataset([NotNull] VtlParser.AggrDatasetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>anSimpleFunction</c>
	/// labeled alternative in <see cref="VtlParser.anFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnSimpleFunction([NotNull] VtlParser.AnSimpleFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lagOrLeadAn</c>
	/// labeled alternative in <see cref="VtlParser.anFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLagOrLeadAn([NotNull] VtlParser.LagOrLeadAnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ratioToReportAn</c>
	/// labeled alternative in <see cref="VtlParser.anFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRatioToReportAn([NotNull] VtlParser.RatioToReportAnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>anSimpleFunctionComponent</c>
	/// labeled alternative in <see cref="VtlParser.anFunctionComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnSimpleFunctionComponent([NotNull] VtlParser.AnSimpleFunctionComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lagOrLeadAnComponent</c>
	/// labeled alternative in <see cref="VtlParser.anFunctionComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLagOrLeadAnComponent([NotNull] VtlParser.LagOrLeadAnComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rankAnComponent</c>
	/// labeled alternative in <see cref="VtlParser.anFunctionComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRankAnComponent([NotNull] VtlParser.RankAnComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ratioToReportAnComponent</c>
	/// labeled alternative in <see cref="VtlParser.anFunctionComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRatioToReportAnComponent([NotNull] VtlParser.RatioToReportAnComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.renameClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRenameClauseItem([NotNull] VtlParser.RenameClauseItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateClause([NotNull] VtlParser.AggregateClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.aggrFunctionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrFunctionClause([NotNull] VtlParser.AggrFunctionClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.calcClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcClauseItem([NotNull] VtlParser.CalcClauseItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.subspaceClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubspaceClauseItem([NotNull] VtlParser.SubspaceClauseItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleScalar</c>
	/// labeled alternative in <see cref="VtlParser.scalarItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleScalar([NotNull] VtlParser.SimpleScalarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>scalarWithCast</c>
	/// labeled alternative in <see cref="VtlParser.scalarItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarWithCast([NotNull] VtlParser.ScalarWithCastContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.joinClauseWithoutUsing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinClauseWithoutUsing([NotNull] VtlParser.JoinClauseWithoutUsingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.joinClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinClause([NotNull] VtlParser.JoinClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.joinClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinClauseItem([NotNull] VtlParser.JoinClauseItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.joinBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinBody([NotNull] VtlParser.JoinBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.joinApplyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinApplyClause([NotNull] VtlParser.JoinApplyClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.partitionByClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartitionByClause([NotNull] VtlParser.PartitionByClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.orderByClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByClause([NotNull] VtlParser.OrderByClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.orderByItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByItem([NotNull] VtlParser.OrderByItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.windowingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowingClause([NotNull] VtlParser.WindowingClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.signedInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedInteger([NotNull] VtlParser.SignedIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.limitClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimitClauseItem([NotNull] VtlParser.LimitClauseItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>groupByOrExcept</c>
	/// labeled alternative in <see cref="VtlParser.groupingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupByOrExcept([NotNull] VtlParser.GroupByOrExceptContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>groupAll</c>
	/// labeled alternative in <see cref="VtlParser.groupingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupAll([NotNull] VtlParser.GroupAllContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHavingClause([NotNull] VtlParser.HavingClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.parameterItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterItem([NotNull] VtlParser.ParameterItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.outputParameterType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputParameterType([NotNull] VtlParser.OutputParameterTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.outputParameterTypeComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputParameterTypeComponent([NotNull] VtlParser.OutputParameterTypeComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.inputParameterType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputParameterType([NotNull] VtlParser.InputParameterTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.rulesetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulesetType([NotNull] VtlParser.RulesetTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarType([NotNull] VtlParser.ScalarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.componentType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentType([NotNull] VtlParser.ComponentTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.datasetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasetType([NotNull] VtlParser.DatasetTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.evalDatasetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalDatasetType([NotNull] VtlParser.EvalDatasetTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.scalarSetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarSetType([NotNull] VtlParser.ScalarSetTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dataPoint</c>
	/// labeled alternative in <see cref="VtlParser.dpRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataPoint([NotNull] VtlParser.DataPointContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dataPointVd</c>
	/// labeled alternative in <see cref="VtlParser.dpRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataPointVd([NotNull] VtlParser.DataPointVdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dataPointVar</c>
	/// labeled alternative in <see cref="VtlParser.dpRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataPointVar([NotNull] VtlParser.DataPointVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>hrRulesetType</c>
	/// labeled alternative in <see cref="VtlParser.hrRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHrRulesetType([NotNull] VtlParser.HrRulesetTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>hrRulesetVdType</c>
	/// labeled alternative in <see cref="VtlParser.hrRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHrRulesetVdType([NotNull] VtlParser.HrRulesetVdTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>hrRulesetVarType</c>
	/// labeled alternative in <see cref="VtlParser.hrRuleset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHrRulesetVarType([NotNull] VtlParser.HrRulesetVarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.valueDomainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueDomainName([NotNull] VtlParser.ValueDomainNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.rulesetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulesetID([NotNull] VtlParser.RulesetIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.rulesetSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulesetSignature([NotNull] VtlParser.RulesetSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignature([NotNull] VtlParser.SignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.ruleClauseDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleClauseDatapoint([NotNull] VtlParser.RuleClauseDatapointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.ruleItemDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleItemDatapoint([NotNull] VtlParser.RuleItemDatapointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.ruleClauseHierarchical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleClauseHierarchical([NotNull] VtlParser.RuleClauseHierarchicalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.ruleItemHierarchical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleItemHierarchical([NotNull] VtlParser.RuleItemHierarchicalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.hierRuleSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierRuleSignature([NotNull] VtlParser.HierRuleSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.valueDomainSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueDomainSignature([NotNull] VtlParser.ValueDomainSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.codeItemRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeItemRelation([NotNull] VtlParser.CodeItemRelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.codeItemRelationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeItemRelationClause([NotNull] VtlParser.CodeItemRelationClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.valueDomainValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueDomainValue([NotNull] VtlParser.ValueDomainValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>conditionConstraint</c>
	/// labeled alternative in <see cref="VtlParser.scalarTypeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionConstraint([NotNull] VtlParser.ConditionConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rangeConstraint</c>
	/// labeled alternative in <see cref="VtlParser.scalarTypeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeConstraint([NotNull] VtlParser.RangeConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.compConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompConstraint([NotNull] VtlParser.CompConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.multModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultModifier([NotNull] VtlParser.MultModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.validationOutput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidationOutput([NotNull] VtlParser.ValidationOutputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.validationMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidationMode([NotNull] VtlParser.ValidationModeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.conditionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionClause([NotNull] VtlParser.ConditionClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.inputMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputMode([NotNull] VtlParser.InputModeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.imbalanceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImbalanceExpr([NotNull] VtlParser.ImbalanceExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.inputModeHierarchy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputModeHierarchy([NotNull] VtlParser.InputModeHierarchyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.outputModeHierarchy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputModeHierarchy([NotNull] VtlParser.OutputModeHierarchyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias([NotNull] VtlParser.AliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarID([NotNull] VtlParser.VarIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.simpleComponentId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleComponentId([NotNull] VtlParser.SimpleComponentIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentID([NotNull] VtlParser.ComponentIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.lists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLists([NotNull] VtlParser.ListsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.erCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErCode([NotNull] VtlParser.ErCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.erLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErLevel([NotNull] VtlParser.ErLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.comparisonOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOperand([NotNull] VtlParser.ComparisonOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.optionalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalExpr([NotNull] VtlParser.OptionalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.optionalExprComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalExprComponent([NotNull] VtlParser.OptionalExprComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.componentRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentRole([NotNull] VtlParser.ComponentRoleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.viralAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitViralAttribute([NotNull] VtlParser.ViralAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.valueDomainID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueDomainID([NotNull] VtlParser.ValueDomainIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.operatorID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorID([NotNull] VtlParser.OperatorIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.routineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutineName([NotNull] VtlParser.RoutineNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] VtlParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.basicScalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicScalarType([NotNull] VtlParser.BasicScalarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VtlParser.retainType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetainType([NotNull] VtlParser.RetainTypeContext context);
}
